import {
  bigint,
  boolean,
  check,
  index,
  integer,
  jsonb,
  pgEnum,
  pgTable,
  primaryKey,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from "drizzle-orm/pg-core";
import { desc, sql } from "drizzle-orm";
import { uuidv7 } from "uuidv7";

// Schema v1 (CLOSED) — see docs/v2-prd.md "Schema v1". Conventions:
// - uuidv7 PKs, app-generated via $defaultFn (postgres:16 has no native uuidv7)
// - sort_order = fractional-index strings (Figma-style)
// - created_at/updated_at timestamptz; updated_at maintained by trigger (migration 0001)
// - NOTIFY trigger on every table (migration 0001)

import { user } from "./auth-schema.js";

// better-auth's tables (user, session, account, verification, apikey) live in
// auth-schema.ts (generated by @better-auth/cli) and are re-exported here so
// the drizzle instance + drizzle-kit see one merged schema. They deliberately
// get NO hitch_notify_change / updated_at triggers — they're not app state,
// and better-auth manages its own timestamps.
export * from "./auth-schema.js";

const id = () =>
  uuid("id")
    .primaryKey()
    .$defaultFn(() => uuidv7());

const createdAt = () => timestamp("created_at", { withTimezone: true }).notNull().defaultNow();
const updatedAt = () => timestamp("updated_at", { withTimezone: true }).notNull().defaultNow();

// ---------------------------------------------------------------------------
// Enums
// ---------------------------------------------------------------------------

export const taskStatus = pgEnum("task_status", ["open", "done"]);
export const authorKind = pgEnum("author_kind", ["user", "agent"]);
export const attachmentState = pgEnum("attachment_state", ["pending", "finalized"]);
export const harness = pgEnum("harness", ["claude", "codex"]);
export const assignmentDesiredState = pgEnum("assignment_desired_state", ["running", "stopped"]);
export const assignmentObservedState = pgEnum("assignment_observed_state", [
  "pending",
  "spawning",
  "running",
  "waiting_input",
  "done",
  "dead",
]);
// chat_status stays the rendered vocabulary, but under the V3 chat-tracking
// design (docs/chat-tracking-redesign.md §3) it is SERVER-DERIVED from the
// three axes below — see src/chatStatus.ts. The daemon reports; it never decides.
export const chatStatus = pgEnum("chat_status", ["busy", "waiting_input", "idle", "dead"]);

// Axis 1 — EXISTENCE. Owned by the machine (process table, keyed by
// (pid, start-time)). Events may never write this. Null = no live observation
// (either a legacy row, or one the absence sweep marked dead).
export const chatExistence = pgEnum("chat_existence", ["running", "dormant", "pending"]);

// Axis 2 — ACTIVITY. Owned by the machine (pidfile self-report, transcript
// mtime delta). `unknown` resolves to idle, NEVER to working: idle beats
// guessing working.
export const chatActivity = pgEnum("chat_activity", ["working", "idle", "unknown"]);

// Axis 3 — BLOCK. Owned by hook events, the only source that can see it.
// Deliberately its own nullable column rather than a status value: a chat can
// be working AND blocked, and collapsing them is what forced the old
// "needs-input folds to working" comparison. Never outlives its process.
export const chatBlock = pgEnum("chat_block", ["permission", "question"]);

// ---------------------------------------------------------------------------
// Intent tables (written by client/CLI)
// ---------------------------------------------------------------------------

export const projects = pgTable(
  "projects",
  {
    id: id(),
    // FK to the better-auth user table (text ids on both sides).
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    // ⚠ machine-specific on a shared table — fine at 1 machine; becomes a
    // project_paths(project_id, machine_id, path) join if a 2nd machine appears.
    repoPath: text("repo_path"),
    sortOrder: text("sort_order").notNull(),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [index("projects_user_id_idx").on(t.userId)],
);

export const sections = pgTable(
  "sections",
  {
    id: id(),
    projectId: uuid("project_id")
      .notNull()
      .references(() => projects.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    sortOrder: text("sort_order").notNull(),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [index("sections_project_id_idx").on(t.projectId)],
);

export const tasks = pgTable(
  "tasks",
  {
    id: id(),
    // Deleting a project deletes its tasks (Todoist semantics); deleting a
    // section drops its tasks back to the project root, never mass-deletes.
    projectId: uuid("project_id").references(() => projects.id, { onDelete: "cascade" }),
    sectionId: uuid("section_id").references(() => sections.id, { onDelete: "set null" }),
    title: text("title").notNull(),
    // Markdown, stored VERBATIM — capture text is sacred, never transform.
    body: text("body").notNull(),
    status: taskStatus("status").notNull().default("open"),
    sortOrder: text("sort_order").notNull(),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
    completedAt: timestamp("completed_at", { withTimezone: true }),
  },
  (t) => [
    index("tasks_project_id_idx").on(t.projectId),
    index("tasks_section_id_idx").on(t.sectionId),
    index("tasks_status_idx").on(t.status),
  ],
);

export const tags = pgTable(
  "tags",
  {
    id: id(),
    // FK to the better-auth user table (text ids on both sides).
    userId: text("user_id")
      .notNull()
      .references(() => user.id, { onDelete: "cascade" }),
    name: text("name").notNull(),
    // Named tint, e.g. "olive" — client owns the palette.
    color: text("color").notNull(),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [uniqueIndex("tags_user_id_name_unique").on(t.userId, t.name)],
);

export const taskTags = pgTable(
  "task_tags",
  {
    taskId: uuid("task_id")
      .notNull()
      .references(() => tasks.id, { onDelete: "cascade" }),
    tagId: uuid("tag_id")
      .notNull()
      .references(() => tags.id, { onDelete: "cascade" }),
    createdAt: createdAt(),
  },
  (t) => [
    primaryKey({ columns: [t.taskId, t.tagId] }),
    index("task_tags_tag_id_idx").on(t.tagId),
  ],
);

// ---------------------------------------------------------------------------
// Execution tables
// ---------------------------------------------------------------------------

export const machines = pgTable("machines", {
  id: id(),
  // FK to the better-auth user table (text ids on both sides).
  userId: text("user_id")
    .notNull()
    .references(() => user.id, { onDelete: "cascade" }),
  name: text("name").notNull(),
  daemonVersion: text("daemon_version").notNull(),
  lastSeenAt: timestamp("last_seen_at", { withTimezone: true }).notNull().defaultNow(),
  // Coverage of the LAST chat snapshot this machine PUT (the whole `window`
  // block of docs/chat-tracking-redesign.md §7, plus its observedAt). The chat
  // rows carry their own last_observed_at, but the snapshot's *coverage* — how
  // far back the daemon looked, the cap, and whether it saw everything — is a
  // property of the tick, not of any row, and was previously dropped on the
  // floor. The Chat Inspector's health strip is the reader: a stale or
  // `truncated` snapshot means every chat row below it is fiction, and that has
  // to be legible before any individual chat is. All nullable: a machine that
  // has never PUT a snapshot has no coverage to report.
  chatSnapshotAt: timestamp("chat_snapshot_at", { withTimezone: true }),
  chatWindowSince: timestamp("chat_window_since", { withTimezone: true }),
  chatWindowCap: integer("chat_window_cap"),
  /** true = coverage was incomplete; the server skipped its death sweep. */
  chatWindowTruncated: boolean("chat_window_truncated"),
  createdAt: createdAt(),
  updatedAt: updatedAt(),
});

// Daemon-created; can exist task-free for ad-hoc chats. ALL columns daemon-written.
//
// V3 chat tracking (docs/chat-tracking-redesign.md): the natural key is
// (machine_id, harness, session_id) — the harness's own session id — and the
// observation columns (existence/activity/block/evidence) arrive as one
// snapshot per tick via PUT /daemon/machines/:id/chat-snapshot. `status` is
// derived from them on the server.
export const chats = pgTable(
  "chats",
  {
    id: id(),
    // NO ACTION on purpose: machines with history shouldn't be silently deletable.
    machineId: uuid("machine_id")
      .notNull()
      .references(() => machines.id),
    projectId: uuid("project_id").references(() => projects.id, { onDelete: "set null" }),
    harness: harness("harness").notNull(),
    title: text("title").notNull(),
    // The harness's own session id: the transcript filename for Claude,
    // session_meta.id for Codex. Nullable only for legacy rows written before
    // the snapshot endpoint existed — everything new carries one.
    sessionId: text("session_id"),
    cwd: text("cwd"),
    // Process identity, not just a pid: (pid, start-time) defeats PID reuse.
    pid: integer("pid"),
    processStartedAt: bigint("process_started_at", { mode: "number" }),
    existence: chatExistence("existence"),
    activity: chatActivity("activity"),
    // Null means NOT blocked. Its own column on purpose — see chatBlock.
    block: chatBlock("block"),
    // What produced the observation: source, mtime age, cursor offsets, ...
    // Read by the Chat Inspector; never interpreted by the status function.
    evidence: jsonb("evidence"),
    lastObservedAt: timestamp("last_observed_at", { withTimezone: true }),
    // Formerly cmux_ref, and NOT NULL — which structurally forbade a chat Hitch
    // didn't launch through cmux. Now nullable "attachment 2": how to focus or
    // close this chat, if we happen to know. A chat with no handle is a
    // complete, correct chat (docs/chat-tracking-redesign.md §4).
    handle: jsonb("handle"),
    status: chatStatus("status").notNull(),
    lastActivityAt: timestamp("last_activity_at", { withTimezone: true }).notNull().defaultNow(),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    index("chats_machine_id_idx").on(t.machineId),
    index("chats_project_id_idx").on(t.projectId),
    // The natural key. Postgres treats NULLs as distinct, so the legacy rows
    // with no session_id don't collide with each other or with anything new.
    uniqueIndex("chats_machine_harness_session_unique").on(t.machineId, t.harness, t.sessionId),
  ],
);

// Hook events relayed verbatim by the daemon out of its spool dir. This is an
// inbox landing zone, NOT a ledger: the server never derives existence or
// activity from it. Its job is to carry `block` and to let the Chat Inspector
// show WHY a chat is in a state, not just what state it is in.
export const chatEvents = pgTable(
  "chat_events",
  {
    id: id(),
    chatId: uuid("chat_id")
      .notNull()
      .references(() => chats.id, { onDelete: "cascade" }),
    // Freeform, not a pgEnum: the hook vocabulary versions faster than a
    // migration should. "block.permission" / "block.question" / "block.clear"
    // are the kinds the server acts on (see routes/daemon.ts).
    kind: text("kind").notNull(),
    // Producer-stamped observation time, not insert time.
    at: timestamp("at", { withTimezone: true }).notNull().defaultNow(),
    payload: jsonb("payload"),
    createdAt: createdAt(),
  },
  (t) => [index("chat_events_chat_id_at_idx").on(t.chatId, desc(t.at))],
);

// One handoff of a task to an agent on a machine. Append-only; created by
// client/CLI (intent) — observed_state and chat_id/worktree are DAEMON-ONLY.
// requested_chat_id is different: it is client intent asking the daemon to
// adopt an already-running chat instead of spawning a new one. The daemon
// validates that request against its machine view and remains the sole writer
// of the authoritative chat_id.
export const assignments = pgTable(
  "assignments",
  {
    id: id(),
    taskId: uuid("task_id")
      .notNull()
      .references(() => tasks.id, { onDelete: "cascade" }),
    // NO ACTION on purpose: machines with history shouldn't be silently deletable.
    machineId: uuid("machine_id")
      .notNull()
      .references(() => machines.id),
    harness: harness("harness").notNull(),
    prompt: text("prompt"),
    // Kickoff-only launch params chosen in the compose UI. Nullable on purpose:
    // an existing row or a client that omits them means "use the harness
    // default" — the daemon passes undefined and the launcher's argv defaults
    // stand (today's behavior). Freeform text, not enums: the model/effort
    // catalog is client-owned and versions faster than a pgEnum should.
    model: text("model"),
    effort: text("effort"),
    desiredState: assignmentDesiredState("desired_state").notNull(),
    reviewedAt: timestamp("reviewed_at", { withTimezone: true }),
    observedState: assignmentObservedState("observed_state").notNull().default("pending"),
    requestedChatId: uuid("requested_chat_id").references(() => chats.id, {
      onDelete: "set null",
    }),
    chatId: uuid("chat_id").references(() => chats.id, { onDelete: "set null" }),
    worktree: text("worktree"),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    index("assignments_task_id_idx").on(t.taskId),
    index("assignments_machine_id_idx").on(t.machineId),
    index("assignments_requested_chat_id_idx").on(t.requestedChatId),
    index("assignments_chat_id_idx").on(t.chatId),
    index("assignments_observed_state_idx").on(t.observedState),
  ],
);

export const comments = pgTable(
  "comments",
  {
    id: id(),
    taskId: uuid("task_id")
      .notNull()
      .references(() => tasks.id, { onDelete: "cascade" }),
    authorKind: authorKind("author_kind").notNull(),
    assignmentId: uuid("assignment_id").references(() => assignments.id, { onDelete: "set null" }),
    body: text("body").notNull(),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    index("comments_task_id_idx").on(t.taskId),
    index("comments_assignment_id_idx").on(t.assignmentId),
  ],
);

export const attachments = pgTable(
  "attachments",
  {
    id: id(),
    // Cascade deletes may orphan S3 objects — accepted for v1.
    taskId: uuid("task_id").references(() => tasks.id, { onDelete: "cascade" }),
    commentId: uuid("comment_id").references(() => comments.id, { onDelete: "cascade" }),
    // S3 object key — never a URL.
    key: text("key").notNull(),
    filename: text("filename").notNull(),
    mime: text("mime").notNull(),
    size: bigint("size", { mode: "number" }).notNull(),
    sha256: text("sha256").notNull(),
    state: attachmentState("state").notNull().default("pending"),
    createdAt: createdAt(),
    updatedAt: updatedAt(),
  },
  (t) => [
    index("attachments_task_id_idx").on(t.taskId),
    index("attachments_comment_id_idx").on(t.commentId),
    check(
      "attachments_exactly_one_parent",
      sql`(${t.taskId} IS NULL) <> (${t.commentId} IS NULL)`,
    ),
  ],
);

// ---------------------------------------------------------------------------
// Row types ($inferSelect) — re-exported through @hitch/server for shared/.
// ---------------------------------------------------------------------------

export type Project = typeof projects.$inferSelect;
export type Section = typeof sections.$inferSelect;
export type Task = typeof tasks.$inferSelect;
export type Tag = typeof tags.$inferSelect;
export type TaskTag = typeof taskTags.$inferSelect;
export type Comment = typeof comments.$inferSelect;
export type Machine = typeof machines.$inferSelect;
export type Chat = typeof chats.$inferSelect;
export type ChatEvent = typeof chatEvents.$inferSelect;
export type Assignment = typeof assignments.$inferSelect;
export type Attachment = typeof attachments.$inferSelect;
